
import { type Reservation, type GiftCardPurchase } from '@/lib/types';

const today = new Date();
const currentYear = today.getFullYear();

export const allReservations: Reservation[] = [
  {
    id: 'res_001',
    activityTitle: 'Pumpkin Picking',
    activitySlug: 'pumpkin-picking',
    activityType: 'Pumpkin Picking',
    date: new Date(currentYear, 9, 25),
    time: '10:00',
    name: 'Alice Johnson',
    email: 'alice.j@example.com',
    phone: '07123456789',
    quantity: 4, // Carload
  },
  {
    id: 'res_002',
    activityTitle: 'Alpaca Walk',
    activitySlug: 'alpaca-walk',
    activityType: 'Alpaca Walk',
    packages: [{ slug: 'adult', title: 'Adult', quantity: 2 }],
    date: new Date(currentYear, 9, 22),
    time: '11:00',
    name: 'Bob Williams',
    email: 'bob.w@example.com',
    quantity: 2,
  },
  {
    id: 'res_003',
    activityTitle: 'Pumpkin Picking',
    activitySlug: 'pumpkin-picking',
    activityType: 'Moonlit Pumpkin Picking',
    date: new Date(currentYear, 9, 24),
    time: '19:00',
    name: 'Charlie Brown',
    email: 'charlie.b@example.com',
    quantity: 2, // Carload
  },
  {
    id: 'res_004',
    activityTitle: 'Alpaca Walk',
    activitySlug: 'alpaca-walk',
    activityType: 'Alpaca Walk',
    packages: [
      { slug: 'child', title: 'Child', quantity: 1 },
      { slug: 'adult', title: 'Adult', quantity: 1 },
    ],
    date: new Date(currentYear, 9, 23),
    time: '13:00',
    name: 'Diana Prince',
    email: 'diana.p@example.com',
    phone: '07987654321',
    quantity: 3,
  },
  {
    id: 'res_005',
    activityTitle: 'Pumpkin Picking',
    activitySlug: 'pumpkin-picking',
    activityType: 'Quiet Pumpkin Picking',
    date: new Date(currentYear, 9, 22),
    time: '15:00',
    name: 'Eve Adams',
    email: 'eve.a@example.com',
    quantity: 3, // Carload
  },
    {
    id: 'res_006',
    activityTitle: 'Alpaca Walk',
    activitySlug: 'alpaca-walk',
    activityType: 'Alpaca Walk',
    packages: [{ slug: 'shared', title: 'Shared Alpaca', quantity: 1 }],
    date: new Date(currentYear, 9, 24),
    time: '11:00',
    name: 'Frank Miller',
    email: 'frank.m@example.com',
    quantity: 2,
  },
  {
    id: 'res_007',
    activityTitle: 'Pumpkin Picking',
    activitySlug: 'pumpkin-picking',
    activityType: 'Pumpkin Picking',
    date: new Date(currentYear, 9, 26),
    time: '11:00',
    name: 'Grace Lee',
    email: 'grace.l@example.com',
    quantity: 5, // Carload
  },
  {
    id: 'res_008',
    activityTitle: 'Alpaca Walk',
    activitySlug: 'alpaca-walk',
    activityType: 'Alpaca Walk',
    packages: [
        { slug: 'adult', title: 'Adult', quantity: 2 },
        { slug: 'spectator', title: 'Spectator', quantity: 1 },
    ],
    date: new Date(currentYear, 9, 16),
    time: '13:00',
    name: 'Heidi Turner',
    email: 'heidi.t@example.com',
    phone: '07555123123',
    quantity: 3,
  },
    {
    id: 'res_009',
    activityTitle: 'Pumpkin Picking',
    activitySlug: 'pumpkin-picking',
    activityType: 'Moonlit Pumpkin Picking',
    date: new Date(currentYear, 9, 25),
    time: '20:00',
    name: 'Ivan Petrov',
    email: 'ivan.p@example.com',
    quantity: 4, // carload
  },
  {
    id: 'res_010',
    activityTitle: 'Pumpkin Picking',
    activitySlug: 'pumpkin-picking',
    activityType: 'Pumpkin Picking',
    date: new Date(currentYear, 9, 27),
    time: '14:00',
    name: 'Judy Alvarez',
    email: 'judy.a@example.com',
    quantity: 2, // carload
  },
];


export const allGiftCardPurchases: GiftCardPurchase[] = [
  {
    id: 'gc_001',
    amount: '25.00',
    senderName: 'Tom Keddie',
    senderEmail: 'tom.k@example.com',
    recipientName: 'Jane Doe',
    recipientEmail: 'jane.doe@example.com',
    message: 'Happy Birthday! Hope you have a magical time.',
    purchaseDate: new Date(2024, 8, 15),
  },
  {
    id: 'gc_002',
    amount: '50.00',
    senderName: 'Alice Johnson',
    senderEmail: 'alice.j@example.com',
    recipientName: 'Bob Williams',
    recipientEmail: 'bob.w@example.com',
    message: 'Enjoy the alpaca walk!',
    purchaseDate: new Date(2024, 8, 20),
  },
  {
    id: 'gc_003',
    amount: '75.00',
    senderName: 'Charlie Brown',
    senderEmail: 'charlie.b@example.com',
    recipientName: 'Diana Prince',
    recipientEmail: 'diana.p@example.com',
    message: '', // No message
    purchaseDate: new Date(2024, 9, 1),
  },
  {
    id: 'gc_004',
    amount: '100.00',
    senderName: 'Eve Adams',
    senderEmail: 'eve.a@example.com',
    recipientName: 'Frank Miller',
    recipientEmail: 'frank.m@example.com',
    message: 'A little something for your next adventure.',
    purchaseDate: new Date(2024, 9, 5),
  },
  {
    id: 'gc_005',
    amount: '30.00',
    senderName: 'Grace Lee',
    senderEmail: 'grace.l@example.com',
    recipientName: 'Heidi Turner',
    recipientEmail: 'heidi.t@example.com',
    message: 'Just because!',
    purchaseDate: new Date(2024, 9, 10),
  },
];
